  " points to specific file vim_bash to find aliases
let $BASH_ENV="~/.vim/vim_bash"

" maps Ctrl + p to use chrome alias to open current file
nnoremap <C-p> :!chrome %<CR>

" checks to see if windows xterm, fixes cursor issues due to WSL
if &term =~ '^xterm'
  " insert mode 
  let &t_SI .= "\<Esc>[5 q"
  " otherwise
  let &t_EI .= "\<Esc>[0 q"
  " 1 or 0 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " Recent versions of xterm (282 or above) also support
  " 5 -> blinking vertical bar
  " 6 -> solid vertical bar
endif


